### ISSUE TITLE
Collection.fetch throws "has no method `_validate` error"

### ISSUE THREAD

**Issue by neverfox** [misteroneill/backbone-model-factory#5]
When I use ModelFactory I get an error similar to [this one](http://stackoverflow.com/questions/10666989/backbone-collection-fetch-throws-object-has-no-method-validate). I don't get the error with a regular Model. Perhaps I'm missing something that I'm required to do differently with a ModelFactory that is used in a collection.

Here's my code (in Coffeescript):
````coffeescript
class Portfolio extends Backbone.ModelFactory
  idAttribute: "_id"

class Portfolios extends Backbone.Collection
  model: Portfolio
  url: "#{config.apiUrl}/portfolios"

portfolios = new Portfolios
portfolios.fetch()
````

**Comment by misteroneill** [comment]
Didn't realize this was still open (2 years later!), but anyone who stumbles on this now should know that this syntax will not work (sorry for not catching that way back then). `Backbone.ModelFactory` is a factory function, so using it in Coffeescript would look like:

```js
Portfolio = Backbone.ModelFactory
  idAttribute: "_id"
```
